import "bootstrap/dist/css/bootstrap.min.css";
import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './_components/navbar/navbar.components'
import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({  
  children, user, employer
}: {
  children: React.ReactNode,
  user: React.ReactNode,
  employer: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <div className="container">
            <div className="row">
              <div className="col-12 py-3">
                <Navbar />
              </div>
            </div>
            <div className="row">
                <div className="col-12">
                {children}
                {
                  employer
                }
                </div>
              </div>
          </div>
        </UserProvider>  
      </body>
    </html>
  )
}
